-- PostgreSQL 스키마 (SQLite database/schema.sql + server/db.js migrate() 최종 형태와 동일한 구조)
-- 날짜·시각은 SQLite와 같이 'YYYY-MM-DD' / 'YYYY-MM-DD HH24:MI:SS' 문자열로 저장합니다.
-- 문자열 정렬이 SQLite(바이트 순서)와 같도록 텍스트 컬럼은 COLLATE "C"를 씁니다.
-- 서버 시작 시 매번 실행되므로 모든 문장은 IF NOT EXISTS로 작성합니다.

CREATE TABLE IF NOT EXISTS employees (
  id                        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  emp_no                    TEXT COLLATE "C" UNIQUE,
  name                      TEXT COLLATE "C" NOT NULL,
  hire_date                 TEXT COLLATE "C" NOT NULL,
  department                TEXT COLLATE "C",
  position                  TEXT COLLATE "C",
  email                     TEXT COLLATE "C",
  notes                     TEXT COLLATE "C",
  is_active                 INTEGER NOT NULL DEFAULT 1,
  created_at                TEXT COLLATE "C" NOT NULL DEFAULT to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  updated_at                TEXT COLLATE "C" NOT NULL DEFAULT to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  terminated_date           TEXT COLLATE "C",
  is_admin                  INTEGER NOT NULL DEFAULT 0,
  workplace                 TEXT COLLATE "C",
  workplace_code            TEXT COLLATE "C",
  department_code           TEXT COLLATE "C",
  job_type                  TEXT COLLATE "C",
  position_code             TEXT COLLATE "C",
  concurrent_dept           TEXT COLLATE "C",
  concurrent_dept_code      TEXT COLLATE "C",
  concurrent_position       TEXT COLLATE "C",
  concurrent_position_code  TEXT COLLATE "C",
  ordinary_wage             DOUBLE PRECISION
);

CREATE INDEX IF NOT EXISTS idx_employees_emp_no ON employees(emp_no);
CREATE INDEX IF NOT EXISTS idx_employees_hire_date ON employees(hire_date);
CREATE INDEX IF NOT EXISTS idx_employees_name ON employees(name);

CREATE TABLE IF NOT EXISTS departments (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT COLLATE "C" NOT NULL UNIQUE,
  created_at  TEXT COLLATE "C" NOT NULL DEFAULT to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS leave_balance_snapshots (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id   INTEGER NOT NULL REFERENCES employees(id) ON DELETE CASCADE DEFERRABLE,
  as_of_date    TEXT COLLATE "C" NOT NULL,
  display_year  INTEGER NOT NULL,
  accrued       DOUBLE PRECISION NOT NULL DEFAULT 0,
  used          DOUBLE PRECISION NOT NULL DEFAULT 0,
  remaining     DOUBLE PRECISION NOT NULL DEFAULT 0,
  source_file   TEXT COLLATE "C",
  imported_at   TEXT COLLATE "C" NOT NULL DEFAULT to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE (employee_id, as_of_date)
);

CREATE TABLE IF NOT EXISTS leave_accruals (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id   INTEGER NOT NULL REFERENCES employees(id) ON DELETE CASCADE DEFERRABLE,
  accrual_date  TEXT COLLATE "C" NOT NULL,
  accrual_type  TEXT COLLATE "C" NOT NULL CHECK (accrual_type IN (
                  'first_year_monthly', 'prorated', 'annual', 'adjustment', 'settlement'
                )),
  amount        DOUBLE PRECISION NOT NULL,
  description   TEXT COLLATE "C",
  is_manual     INTEGER NOT NULL DEFAULT 0,
  created_by    TEXT COLLATE "C" DEFAULT 'system',
  created_at    TEXT COLLATE "C" NOT NULL DEFAULT to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  updated_at    TEXT COLLATE "C" NOT NULL DEFAULT to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')
);

CREATE INDEX IF NOT EXISTS idx_leave_accruals_employee ON leave_accruals(employee_id);

CREATE TABLE IF NOT EXISTS leave_usages (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id    INTEGER NOT NULL REFERENCES employees(id) ON DELETE CASCADE DEFERRABLE,
  usage_date     TEXT COLLATE "C" NOT NULL,
  usage_type     TEXT COLLATE "C" NOT NULL DEFAULT 'full' CHECK (usage_type IN ('full', 'half')),
  days           DOUBLE PRECISION NOT NULL,
  reason         TEXT COLLATE "C",
  status         TEXT COLLATE "C" NOT NULL DEFAULT 'approved' CHECK (status IN ('approved', 'pending', 'rejected')),
  created_by     TEXT COLLATE "C" DEFAULT 'system',
  created_at     TEXT COLLATE "C" NOT NULL DEFAULT to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  updated_at     TEXT COLLATE "C" NOT NULL DEFAULT to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  approved_by    INTEGER,
  approved_at    TEXT COLLATE "C",
  reject_reason  TEXT COLLATE "C",
  approval_step  TEXT COLLATE "C"
);

CREATE INDEX IF NOT EXISTS idx_leave_usages_date ON leave_usages(usage_date);
CREATE INDEX IF NOT EXISTS idx_leave_usages_employee ON leave_usages(employee_id);

CREATE TABLE IF NOT EXISTS users (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id    INTEGER NOT NULL UNIQUE REFERENCES employees(id) ON DELETE CASCADE DEFERRABLE,
  username       TEXT COLLATE "C" NOT NULL UNIQUE,
  password_hash  TEXT COLLATE "C" NOT NULL,
  created_at     TEXT COLLATE "C" NOT NULL DEFAULT to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS app_meta (
  key    TEXT COLLATE "C" PRIMARY KEY,
  value  TEXT COLLATE "C" NOT NULL
);

CREATE TABLE IF NOT EXISTS approval_mappings (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id      INTEGER NOT NULL REFERENCES employees(id) ON DELETE CASCADE DEFERRABLE,
  role             TEXT COLLATE "C" NOT NULL,
  workplace_code   TEXT COLLATE "C",
  department_code  TEXT COLLATE "C",
  created_at       TEXT COLLATE "C" NOT NULL DEFAULT to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS approval_seats (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  seat_key     TEXT COLLATE "C" NOT NULL UNIQUE,
  title        TEXT COLLATE "C" NOT NULL,
  step_role    TEXT COLLATE "C" NOT NULL,
  employee_id  INTEGER REFERENCES employees(id) ON DELETE SET NULL DEFERRABLE,
  sort_order   INTEGER NOT NULL DEFAULT 0,
  created_at   TEXT COLLATE "C" NOT NULL DEFAULT to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  updated_at   TEXT COLLATE "C" NOT NULL DEFAULT to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS approval_seat_scopes (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  seat_id          INTEGER NOT NULL REFERENCES approval_seats(id) ON DELETE CASCADE DEFERRABLE,
  workplace_code   TEXT COLLATE "C",
  department_code  TEXT COLLATE "C" NOT NULL,
  department_name  TEXT COLLATE "C",
  UNIQUE (seat_id, department_code)
);

CREATE TABLE IF NOT EXISTS leave_settlement_ordinary_wages (
  employee_id    INTEGER PRIMARY KEY REFERENCES employees(id) ON DELETE CASCADE DEFERRABLE,
  ordinary_wage  DOUBLE PRECISION,
  updated_at     TEXT COLLATE "C" NOT NULL DEFAULT to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS leave_approval_logs (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  leave_usage_id   INTEGER REFERENCES leave_usages(id) ON DELETE SET NULL DEFERRABLE,
  employee_id      INTEGER NOT NULL REFERENCES employees(id) ON DELETE CASCADE DEFERRABLE,
  actor_id         INTEGER REFERENCES employees(id) ON DELETE SET NULL DEFERRABLE,
  action           TEXT COLLATE "C" NOT NULL CHECK (action IN ('submit', 'auto_approve', 'step_approve', 'approve', 'reject')),
  step             TEXT COLLATE "C",
  note             TEXT COLLATE "C",
  usage_date       TEXT COLLATE "C" NOT NULL,
  usage_type       TEXT COLLATE "C" NOT NULL,
  days             DOUBLE PRECISION NOT NULL,
  reason           TEXT COLLATE "C",
  employee_emp_no  TEXT COLLATE "C",
  employee_name    TEXT COLLATE "C" NOT NULL,
  workplace        TEXT COLLATE "C",
  workplace_code   TEXT COLLATE "C",
  department       TEXT COLLATE "C",
  position         TEXT COLLATE "C",
  actor_emp_no     TEXT COLLATE "C",
  actor_name       TEXT COLLATE "C",
  actor_position   TEXT COLLATE "C",
  created_at       TEXT COLLATE "C" NOT NULL DEFAULT to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')
);

CREATE INDEX IF NOT EXISTS idx_leave_approval_logs_created ON leave_approval_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_leave_approval_logs_employee ON leave_approval_logs(employee_id);
CREATE INDEX IF NOT EXISTS idx_leave_approval_logs_action ON leave_approval_logs(action);

CREATE TABLE IF NOT EXISTS leave_month_reports (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  year          INTEGER NOT NULL,
  month         INTEGER NOT NULL,
  as_of_date    TEXT COLLATE "C" NOT NULL,
  generated_by  INTEGER,
  payload       TEXT COLLATE "C" NOT NULL,
  generated_at  TEXT COLLATE "C" NOT NULL DEFAULT to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE (year, month)
);

CREATE TABLE IF NOT EXISTS leave_pay_settlements (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  year          INTEGER NOT NULL,
  month         INTEGER NOT NULL,
  as_of_date    TEXT COLLATE "C" NOT NULL,
  generated_by  INTEGER,
  payload       TEXT COLLATE "C" NOT NULL,
  generated_at  TEXT COLLATE "C" NOT NULL DEFAULT to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE (year, month)
);

CREATE TABLE IF NOT EXISTS leave_event_settlements (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  year          INTEGER NOT NULL UNIQUE,
  as_of_date    TEXT COLLATE "C" NOT NULL,
  generated_by  INTEGER,
  payload       TEXT COLLATE "C" NOT NULL,
  generated_at  TEXT COLLATE "C" NOT NULL DEFAULT to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS mail_settings (
  id           INTEGER PRIMARY KEY CHECK (id = 1),
  enabled      INTEGER NOT NULL DEFAULT 0,
  imap_host    TEXT COLLATE "C",
  imap_port    INTEGER,
  imap_secure  TEXT COLLATE "C",
  smtp_host    TEXT COLLATE "C",
  smtp_port    INTEGER,
  smtp_secure  TEXT COLLATE "C",
  username     TEXT COLLATE "C",
  password     TEXT COLLATE "C",
  from_name    TEXT COLLATE "C",
  from_email   TEXT COLLATE "C",
  app_url      TEXT COLLATE "C",
  updated_at   TEXT COLLATE "C" NOT NULL DEFAULT to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')
);

CREATE OR REPLACE VIEW v_employee_leave_summary AS
SELECT
  e.id,
  e.emp_no,
  e.name,
  e.hire_date,
  e.department,
  e.position,
  e.notes,
  lbs.as_of_date,
  lbs.display_year,
  lbs.accrued,
  lbs.used,
  lbs.remaining
FROM employees e
LEFT JOIN leave_balance_snapshots lbs ON lbs.employee_id = e.id
WHERE e.is_active = 1;
