-- 인사기록카드: 기본정보·병역(1인 1행)과 학력·경력·자격·발령·교육·평가 이력(여러 행)
CREATE TABLE IF NOT EXISTS employee_profiles (
  employee_id         INTEGER PRIMARY KEY REFERENCES employees(id) ON DELETE CASCADE DEFERRABLE,
  birth_date          TEXT COLLATE "C",
  gender              TEXT COLLATE "C",
  mobile_phone        TEXT COLLATE "C",
  personal_email      TEXT COLLATE "C",
  address             TEXT COLLATE "C",
  emergency_name      TEXT COLLATE "C",
  emergency_relation  TEXT COLLATE "C",
  emergency_phone     TEXT COLLATE "C",
  military_status     TEXT COLLATE "C",
  military_branch     TEXT COLLATE "C",
  military_rank       TEXT COLLATE "C",
  military_start      TEXT COLLATE "C",
  military_end        TEXT COLLATE "C",
  military_discharge  TEXT COLLATE "C",
  military_notes      TEXT COLLATE "C",
  updated_by          INTEGER,
  updated_at          TEXT COLLATE "C" NOT NULL DEFAULT to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS employee_records (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id   INTEGER NOT NULL REFERENCES employees(id) ON DELETE CASCADE DEFERRABLE,
  category      TEXT COLLATE "C" NOT NULL CHECK (category IN (
                  'education', 'career', 'license', 'appointment', 'training', 'evaluation'
                )),
  start_date    TEXT COLLATE "C",
  end_date      TEXT COLLATE "C",
  title         TEXT COLLATE "C",
  organization  TEXT COLLATE "C",
  result        TEXT COLLATE "C",
  detail        TEXT COLLATE "C",
  notes         TEXT COLLATE "C",
  updated_by    INTEGER,
  created_at    TEXT COLLATE "C" NOT NULL DEFAULT to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  updated_at    TEXT COLLATE "C" NOT NULL DEFAULT to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')
);

CREATE INDEX IF NOT EXISTS idx_employee_records_employee ON employee_records(employee_id, category);
