-- 근태 관리: 반차 오전/오후 구분, 사업장 근무시간·허용 IP, 출퇴근 기록·변경 이력, 월 마감
ALTER TABLE leave_usages ADD COLUMN IF NOT EXISTS half_period TEXT COLLATE "C";

CREATE TABLE IF NOT EXISTS attendance_sites (
  workplace_code  TEXT COLLATE "C" PRIMARY KEY,
  name            TEXT COLLATE "C" NOT NULL,
  work_start      TEXT COLLATE "C" NOT NULL,
  work_end        TEXT COLLATE "C" NOT NULL,
  lunch_start     TEXT COLLATE "C" NOT NULL,
  lunch_end       TEXT COLLATE "C" NOT NULL,
  grace_minutes   INTEGER NOT NULL DEFAULT 15,
  ip_ranges       TEXT COLLATE "C" NOT NULL DEFAULT '',
  updated_by      INTEGER,
  updated_at      TEXT COLLATE "C" NOT NULL DEFAULT to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')
);

INSERT INTO attendance_sites (workplace_code, name, work_start, work_end, lunch_start, lunch_end, grace_minutes, ip_ranges)
VALUES
  ('1', '서울', '08:30', '17:30', '11:40', '12:40', 15, E'175.192.184.0/28\n192.168.80.0/24'),
  ('2', '천안', '08:00', '17:00', '12:00', '13:00', 15, '221.145.232.0/25'),
  ('3', '충주', '08:00', '17:00', '12:00', '13:00', 15, E'59.31.6.0/27\n59.31.6.64/26\n121.191.197.128/27\n128.231.154.128/25')
ON CONFLICT (workplace_code) DO NOTHING;

CREATE TABLE IF NOT EXISTS attendance_records (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id      INTEGER NOT NULL REFERENCES employees(id) ON DELETE CASCADE DEFERRABLE,
  work_date        TEXT COLLATE "C" NOT NULL,
  check_in_at      TEXT COLLATE "C",
  check_in_ip      TEXT COLLATE "C",
  check_in_type    TEXT COLLATE "C",
  check_in_place   TEXT COLLATE "C",
  check_out_at     TEXT COLLATE "C",
  check_out_ip     TEXT COLLATE "C",
  check_out_type   TEXT COLLATE "C",
  check_out_place  TEXT COLLATE "C",
  corrected        INTEGER NOT NULL DEFAULT 0,
  note             TEXT COLLATE "C",
  created_at       TEXT COLLATE "C" NOT NULL DEFAULT to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  updated_at       TEXT COLLATE "C" NOT NULL DEFAULT to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE (employee_id, work_date)
);

CREATE INDEX IF NOT EXISTS idx_attendance_records_date ON attendance_records(work_date);

CREATE TABLE IF NOT EXISTS attendance_logs (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id  INTEGER NOT NULL REFERENCES employees(id) ON DELETE CASCADE DEFERRABLE,
  work_date    TEXT COLLATE "C" NOT NULL,
  action       TEXT COLLATE "C" NOT NULL,
  occurred_at  TEXT COLLATE "C" NOT NULL,
  ip           TEXT COLLATE "C",
  work_type    TEXT COLLATE "C",
  place        TEXT COLLATE "C",
  actor_id     INTEGER,
  reason       TEXT COLLATE "C",
  detail       TEXT COLLATE "C"
);

CREATE INDEX IF NOT EXISTS idx_attendance_logs_employee ON attendance_logs(employee_id, work_date);

CREATE TABLE IF NOT EXISTS attendance_closings (
  year       INTEGER NOT NULL,
  month      INTEGER NOT NULL,
  closed_by  INTEGER,
  closed_at  TEXT COLLATE "C" NOT NULL DEFAULT to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (year, month)
);
