-- 인사기록카드 입사 증명서류. content 는 암호화한 파일 내용(enc:v1: + base64)입니다.
CREATE TABLE IF NOT EXISTS employee_documents (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id   INTEGER NOT NULL REFERENCES employees(id) ON DELETE CASCADE DEFERRABLE,
  doc_type      TEXT COLLATE "C" NOT NULL,
  file_name     TEXT COLLATE "C" NOT NULL,
  extension     TEXT COLLATE "C" NOT NULL,
  size_bytes    INTEGER NOT NULL,
  sha256        TEXT COLLATE "C" NOT NULL,
  notes         TEXT COLLATE "C",
  content       TEXT COLLATE "C" NOT NULL,
  uploaded_by   INTEGER,
  created_at    TEXT COLLATE "C" NOT NULL DEFAULT to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')
);

CREATE INDEX IF NOT EXISTS idx_employee_documents_employee ON employee_documents(employee_id, id);
